[workspace]
resolver = "2"
members = [
    "secret-sharing",
    "dist-primitive",
    "mpc-net",
    "client",
    "gkr"
, "hyperplonk"]

[profile.bench]
opt-level = 3

[profile.release]
debug = true
